src/AdBundle/Entity/Advert.php
<?php

namespace AdBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Advert
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="AdBundle\Repository\AdvertRepository")
 */
class Advert
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @Assert\NotBlank()
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

    /**
     * @var string
     *
     * @Assert\Length(max = 4096)
     * @Assert\NotBlank()
     * @ORM\Column(name="description", type="text")
     */
    private $description;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime")
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime")
     */
    private $updatedAt;

    /**
     * @var boolean
     *
     * @ORM\Column(name="is_enabled", type="boolean")
     */
    private $isEnabled;

    /**
     * @ORM\OneToMany(targetEntity="AdvertImage", mappedBy="advert")
     */
    protected $images;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->images    = (new ArrayCollection());
        $this->createdAt = (new \DateTime());
        $this->updatedAt = (new \DateTime());
        $this->isEnabled = true;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Advert
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Advert
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return Advert
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     * @return Advert
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime 
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set isEnabled
     *
     * @param boolean $isEnabled
     * @return Advert
     */
    public function setIsEnabled($isEnabled)
    {
        $this->isEnabled = $isEnabled;

        return $this;
    }

    /**
     * Get isEnabled
     *
     * @return boolean 
     */
    public function getIsEnabled()
    {
        return $this->isEnabled;
    }

    /**
     * Add images
     *
     * @param \AdBundle\Entity\AdvertImage $images
     * @return Advert
     */
    public function addImage(AdvertImage $images)
    {
        $this->images[] = $images;

        return $this;
    }

    /**
     * Remove images
     *
     * @param \AdBundle\Entity\AdvertImage $images
     */
    public function removeImage(AdvertImage $images)
    {
        $this->images->removeElement($images);
    }

    /**
     * Get images
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getImages()
    {
        return $this->images;
    }

    public function getThumb()
    {
        return null;
    }
}

src/AdBundle/Form/App/AdvertType.php
<?php

namespace AdBundle\Form\App;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdvertType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', 'text', [
                'label' => 'Заголовок'
            ])
            ->add('description', 'textarea', [
                'label' => 'Описание'
            ])
            ->add('images', 'collection', [
                'label' => 'Изображение',
                'type' => new AdvertImageType()
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AdBundle\Entity\Advert'
        ));
    }

    public function getName()
    {
        return 'advert';
    }
}

src/AdBundle/Controller/App/AdvertController.php
<?php

namespace AdBundle\Controller\App;

use AdBundle\Entity\Advert;
use AdBundle\Form\App\AdvertType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request;

/**
 * Class AdvertController
 * @package AdBundle\Controller\App
 * @Route("/advert")
 */
class AdvertController extends Controller
{
    /**
     * @Route("/list", name="app_advert_list")
     * @Template()
     */
    public function indexAction()
    {
        $em = $this->get('doctrine');
        $er = $em->getRepository('AdBundle:Advert');

        return [
            'adverts' => $er->findBy([], ['createdAt' => 'desc'])
        ];
    }

    /**
     * @Route("/show/id{id}", name="app_advert_show")
     * @Template()
     */
    public function showAction($id)
    {
        $em = $this->get('doctrine');
        $er = $em->getRepository('AdBundle:Advert');

        return [
            'advert' => $er->findOneBy(['id' => $id])
        ];
    }

    /**
     * @param Request $request
     * @Route("/create", name="app_advert_create")
     * @Template()
     * @return array
     */
    public function createAction(Request $request)
    {
        $em = $this->get('doctrine')->getManager();
        $er = $em->getRepository('AdBundle:Advert');
        $advert = new Advert();

        $form = $this->generateCreateForm($advert);
        $form->handleRequest($request);

        if ($request->isMethod('POST')) {
            if ($form->isValid()) {

                $em->persist($advert);
                $em->flush();

                return $this->redirectToRoute('app_advert_list');
            } else {

            }
        }

        return [
            'form' => $form->createView()
        ];
    }

    /**
     * @param Advert $advert
     * @return \Symfony\Component\Form\Form
     */
    public function generateCreateForm(Advert $advert)
    {
        /** @var \Symfony\Component\Form\Form $form */
        $form = $this->createForm(new AdvertType(), $advert, [
            'action' => $this->generateUrl('app_advert_create'),
        ]);

        $form->add('submin', 'submit', [
            'label' => 'Добавить'
        ]);

        return $form;
    }
}

src/AdBundle/Controller/Inside/AdvertController.php
<?php

namespace AdBundle\Controller\Inside;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

/**
 * Class AdvertController
 * @package AdBundle\Controller\Inside
 * @Route("/inside/advert")
 */
class AdvertController extends Controller
{
    /**
     * @Route("/list", name="inside_advert_list")
     * @Template()
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getEntityManager();
        $er = $em->getRepository('AdBundle:Category');

        $category = $er->findOneBy(['id' => 15]);


        $em = $this->get('doctrine');
        $er = $em->getRepository('AdBundle:Advert');

        return [
            'adverts' => $er->findBy([], ['createdAt' => 'desc']),
            'category' => $category
        ];
    }

    /**
     * @Route("/show/id{id}", name="inside_advert_show")
     * @Template()
     */
    public function showAction($id)
    {
        $em = $this->get('doctrine');
        $er = $em->getRepository('AdBundle:Advert');

        return [
            'advert' => $er->findOneBy(['id' => $id])
        ];
    }
}

src/AdBundle/Resources/views/App/Advert/create.html.twig
{% extends '@Default/App/layout.html.twig' %}

{% set title = 'Создание обявления' %}
{% set breadcrumbs = [
{title: 'Обявления', path: path('app_advert_list')},
{title: 'Создание обявления'}
] %}

{% block content %}
    <div class="row">
        <div class="col-md-3">

        </div>
        <div class="col-md-9">
            {{ form(form) }}
        </div>
    </div>
{% endblock %}

src/AdBundle/Resources/views/App/Advert/index.html.twig
{% extends '@Default/App/layout.html.twig' %}

{% set title = 'Обявления' %}
{% set breadcrumbs = {title: 'Обявления'} %}

{% block content %}
    {% if adverts|length > 0 %}
        {% for advert in adverts %}
            <div class="b-col-default-indent">
                <div class="col-md-12">
                    <div class="b-product-preview-row f-product-preview-row">
                        <div class="row">
                            <div class="b-product-preview-row__img">
                                <img data-retina="" src="{{ image(advert.thumb).cropResize(200).jpeg }}" width="200">
                            </div>
                            <div class="b-product-preview-row__content">
                                <a href="{{ path('app_advert_show', {id: advert.id}) }}" class="b-product-preview-row_title f-primary-b f-title-medium f-uppercase">{{ advert.title }}</a>
                                <div class="b-portfolio_info_rating">
                                    <span class="b-product-preview-row_price f-primary-b c-default f-title-medium">$ 239</span>
                                    <span class="b-rating_bord hidden-xs"></span>
                                    <div class="b-stars-group f-stars-group">
                                        <i class="fa fa-star is-active-stars"></i>
                                        <i class="fa fa-star is-active-stars"></i>
                                        <i class="fa fa-star is-active-stars"></i>
                                        <i class="fa fa-star is-active-stars"></i>
                                        <i class="fa fa-star"></i>
                                    </div>
                                    <span class="b-rating_bord hidden-xs"></span>
                                    <div class="b-portfolio_rating_category">
                                        <span class="f-portfolio_category_title">Categoires :</span>
                                        <a href="#" class="f-portfolio_category_name f-more">Women</a>
                                    </div>
                                </div>
                                <p class="b-product-preview-row_description c-senary">
                                    {{ advert.description|slice(0, 60) }}...
                                </p>
                                <div>
                                    <a class="btn btn-default" href="{{ path('app_advert_show', {id:advert.id}) }}">
                                        <i class="fa fa-circle-o-notch"></i> Просмотреть
                                    </a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="alert alert-info">
            No results
        </div>
    {% endif %}
{% endblock %}

src/AdBundle/Resources/views/App/Advert/show.html.twig
{% extends '@Default/App/layout.html.twig' %}

{% set title = 'Просмотр обявления' %}
{% set breadcrumbs = [
{title: 'Обявления', path:path('app_advert_list')},
{title: 'Просмотр'}
] %}

{% block content %}
    <h1>{{ advert.title }}</h1>
    <div class="well">
        {{ advert.description }}
    </div>
{% endblock %}